"""Emit TypeScript interface declarations from the Pydantic response models.

Usage::

    python -m rt_hardware.scripts.dump_types

Writes ``../../../platform/frontend/src/types.gen.ts`` (i.e. into the sibling
platform package's frontend) from this script's location. The frontend
imports from this file; the few platform-only response types (queue config,
queue status) are hand-maintained in ``platform/frontend/src/queue.ts``
because the platform package is not a Python import of this one.
"""
from __future__ import annotations

import dataclasses
import sys
import types
from pathlib import Path
from typing import Any, Iterable, Literal, get_args, get_origin

from pydantic import BaseModel

from rt_hardware.models import state


OUTPUT_PATH = (
    Path(__file__).resolve().parents[3].parent
    / "platform"
    / "frontend"
    / "src"
    / "types.gen.ts"
)


# Models exported to the frontend, in the order they should appear. Keeping
# this ordered (rather than scanning the module's globals) makes the diff
# readable when a model is added or removed.
EXPORTED_MODELS: tuple[type[BaseModel], ...] = (
    state.ConnectionStatus,
    state.MotorSnapshot,
    state.HostStats,
    state.PollStats,
    state.LnaStatus,
    state.RoboClawTelemetry,
    state.AltAzPoint,
    state.HardSafetyLimits,
    state.TelescopeConfig,
    state.SkyOverlay,
    state.CommandArg,
    state.CommandInfo,
    state.CommandResult,
    state.GoesSatelliteInfo,
    state.ObservationInfo,
    state.GoesProduct,
)

# Type aliases emitted as TypeScript union literals.
EXPORTED_LITERALS: tuple[tuple[str, tuple[Any, ...]], ...] = (
    ("ConnectionMode", get_args(state.ConnectionMode)),
    ("LnaState", get_args(state.LnaState)),
    ("ArgType", get_args(state.ArgType)),
    ("ObservationMode", get_args(state.ObservationMode)),
    ("GoesStage", get_args(state.GoesStage)),
    ("GoesProductKind", get_args(state.GoesProductKind)),
)

# Hand-written types that don't have a Pydantic counterpart but live next to
# the generated ones because the frontend imports them from `./types`.
EXTRA_DECLARATIONS = """\
export interface RaDecTarget {
  ra_deg: number;
  dec_deg: number;
}
"""


@dataclasses.dataclass(frozen=True)
class _Emit:
    line: str


def _ts_type(py_type: Any) -> str:
    """Map a Python annotation onto its TypeScript spelling."""
    if py_type is type(None):
        return "null"
    if py_type is str:
        return "string"
    if py_type in (int, float):
        return "number"
    if py_type is bool:
        return "boolean"
    if py_type is Any:
        return "unknown"

    origin = get_origin(py_type)
    if origin is Literal:
        return " | ".join(_literal(v) for v in get_args(py_type))
    if origin in (list, tuple):
        args = get_args(py_type)
        return f"{_ts_type(args[0])}[]" if args else "unknown[]"
    if origin is dict:
        k, v = get_args(py_type)
        return f"Record<{_ts_type(k)}, {_ts_type(v)}>"
    if origin in (types.UnionType, ):  # X | Y syntax
        return " | ".join(_ts_type(arg) for arg in get_args(py_type))
    # typing.Union also lands here via get_origin on python <3.10 syntax.
    if origin is not None and origin.__class__.__name__ == "_SpecialForm":
        # e.g. Union[...]; fall through to args
        return " | ".join(_ts_type(arg) for arg in get_args(py_type))

    if isinstance(py_type, type) and issubclass(py_type, BaseModel):
        return py_type.__name__

    raise TypeError(f"Don't know how to emit TypeScript for {py_type!r}")


def _literal(value: Any) -> str:
    if isinstance(value, str):
        return f"'{value}'"
    if isinstance(value, bool):
        return "true" if value else "false"
    return repr(value)


def _emit_interface(model: type[BaseModel]) -> Iterable[str]:
    yield f"export interface {model.__name__} {{"
    for field_name, info in model.model_fields.items():
        ts = _ts_type(info.annotation)
        # In TS, "X | null" reads more naturally than "X | undefined" for
        # JSON-over-the-wire optionals — the backend serialises None as null.
        yield f"  {field_name}: {ts};"
    yield "}"
    yield ""


def _emit_literal_alias(name: str, values: tuple[Any, ...]) -> Iterable[str]:
    union = " | ".join(_literal(v) for v in values)
    yield f"export type {name} = {union};"


def render() -> str:
    lines: list[str] = [
        "// AUTO-GENERATED by `python -m rt_hardware.scripts.dump_types`.",
        "// Do not edit by hand - re-run the script and commit the result.",
        "",
    ]
    for name, values in EXPORTED_LITERALS:
        lines.extend(_emit_literal_alias(name, values))
    lines.append("")
    for model in EXPORTED_MODELS:
        lines.extend(_emit_interface(model))
    lines.append(EXTRA_DECLARATIONS)
    return "\n".join(lines)


def main() -> None:
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(render(), encoding="utf-8")
    sys.stdout.write(f"Wrote {OUTPUT_PATH}\n")


if __name__ == "__main__":
    main()
