// AUTO-GENERATED by `python -m radiotelescope.scripts.dump_types`.
// Do not edit by hand - re-run the script and commit the result.

export type ConnectionMode = 'serial' | 'disconnected' | 'error';
export type LnaState = 'on' | 'off' | 'unknown' | 'fault';
export type ArgType = 'u8' | 'u16' | 's16' | 'u32' | 's32' | 'bool';

export interface ConnectionStatus {
  mode: 'serial' | 'disconnected' | 'error';
  port: string;
  baudrate: number;
  address: number;
  connected: boolean;
  message: string | null;
}

export interface MotorSnapshot {
  command: number;
  pwm: number | null;
  current_a: number | null;
  encoder: number | null;
  encoder_status: number | null;
  speed_qpps: number | null;
  raw_speed_qpps: number | null;
  average_speed_qpps: number | null;
  speed_error_qpps: number | null;
  position_error: number | null;
}

export interface HostStats {
  cpu_temp_c: number | null;
  load_1m: number | null;
  load_5m: number | null;
  load_15m: number | null;
  cpu_count: number | null;
  memory_total_mb: number | null;
  memory_available_mb: number | null;
  memory_used_percent: number | null;
  disk_total_gb: number | null;
  disk_free_gb: number | null;
  disk_used_percent: number | null;
  uptime_s: number | null;
}

export interface PollStats {
  target_hz: number;
  actual_hz: number | null;
  last_tick_age_s: number | null;
}

export interface LnaStatus {
  state: 'on' | 'off' | 'unknown' | 'fault';
  label: string;
  detail: string | null;
}

export interface RoboClawTelemetry {
  connection: ConnectionStatus;
  timestamp: number;
  poll: PollStats | null;
  firmware: string | null;
  main_battery_v: number | null;
  logic_battery_v: number | null;
  temperature_c: number | null;
  temperature_2_c: number | null;
  status: number | null;
  status_flags: string[];
  buffer_depths: Record<string, number | null>;
  encoder_modes: Record<string, number | null>;
  motors: Record<string, MotorSnapshot>;
  host: HostStats;
  last_error: string | null;
  altitude_deg: number | null;
  azimuth_deg: number | null;
  ra_deg: number | null;
  dec_deg: number | null;
}

export interface AltAzPoint {
  altitude_deg: number;
  azimuth_deg: number;
}

export interface HardSafetyLimits {
  altitude_min_deg: number;
  altitude_max_deg: number;
  azimuth_min_deg: number;
  azimuth_max_deg: number;
}

export interface TelescopeConfig {
  beam_fwhm_deg: number;
  goto_speed_qpps: number;
  goto_accel_qpps2: number;
  goto_decel_qpps2: number;
  observer_latitude_deg: number;
  observer_longitude_deg: number;
  hard_safety_limits: HardSafetyLimits;
}

export interface SkyOverlay {
  id: string;
  label: string;
  ra_deg: number;
  dec_deg: number;
  color: string;
  kind?: 'source' | 'satellite';
  altitude_deg?: number;
  azimuth_deg?: number;
}

export interface CommandArg {
  name: string;
  type: 'u8' | 'u16' | 's16' | 'u32' | 's32' | 'bool';
  label: string;
  min: number | null;
  max: number | null;
  default: number | boolean | null;
}

export interface CommandInfo {
  id: string;
  name: string;
  group: string;
  description: string;
  command: number;
  kind: 'read' | 'write' | 'motion' | 'config';
  dangerous: boolean;
  args: CommandArg[];
}

export interface CommandResult {
  command_id: string;
  ok: boolean;
  response: Record<string, unknown>;
  error: string | null;
}

export interface QueueStatus {
  token: string;
  is_active: boolean;
  position: number;
  queue_length: number;
  lease_remaining_s: number | null;
  idle_remaining_s: number | null;
  has_active_user: boolean;
}

export type TelescopeState = 'operational' | 'maintenance' | 'closed';

export interface TelescopeStatus {
  state: TelescopeState;
  message: string | null;
  updated_at: string | null;
  updated_by_ip_hash: string | null;
}

export interface QueueConfigResponse {
  enabled: boolean;
  turnstile_site_key: string;
  turnstile_enabled: boolean;
  max_session_seconds: number;
  idle_timeout_seconds: number;
  beta_password_enabled: boolean;
  telescope_status: TelescopeStatus;
}

export interface RaDecTarget {
  ra_deg: number;
  dec_deg: number;
}

// ─── GOES observation mode ─────────────────────────────────────────────────

export type ObservationMode = 'hydrogen_line' | 'goes';
export type GoesStage = 'idle' | 'searching' | 'signal' | 'frames' | 'data' | 'fault' | 'unavailable';
export type GoesProductKind = 'image' | 'text' | 'binary';

export interface GoesSatelliteInfo {
  id: string;
  name: string;
  longitude_deg: number;
  azimuth_deg: number;
  elevation_deg: number;
  range_km: number;
  visible: boolean;
  is_target: boolean;
}

export interface ObservationInfo {
  mode: ObservationMode;
  downlink_freq_mhz: number | null;
  symbol_rate_baud: number | null;
  target_satellite_id: string | null;
  satellites: GoesSatelliteInfo[];
  /** Set by the platform proxy when the hardware gateway was unreachable. */
  degraded?: boolean;
}

export interface GoesProduct {
  id: string;
  kind: GoesProductKind;
  name: string;
  /** goesproc handler subdirectory, e.g. "images/goes19/2026-06-12". */
  group: string | null;
  size_bytes: number;
  created_at: number;
  media_type: string;
  preview: string | null;
}

export interface GoesProductList {
  total: number;
  products: GoesProduct[];
}

/** One status frame from /ws/goes — goesrecv demod/decoder stats merged
 *  with the product index. */
export interface GoesFrame {
  timestamp: number;
  stage: GoesStage;
  mode: string;
  snr_db: number | null;
  snr_lock_db: number;
  freq_offset_hz: number | null;
  /** SDR/AGC gain reported by goesrecv (higher = weaker signal). */
  gain: number | null;
  constellation: Array<[number, number]>;
  demod_locked: boolean;
  frame_lock: boolean;
  symbol_rate_baud: number;
  frames_total: number;
  frames_bad: number;
  /** Rolling average of Viterbi-corrected bits per frame. */
  viterbi_errors_avg: number | null;
  rs_corrected: number;
  skipped_symbols: number;
  vcdu_total: number;
  vcdu_fill: number;
  vcdu_counts: Record<string, number>;
  products_total: number;
  last_product_at: number | null;
  data_rate_kbps: number;
}

export interface GoesStatus {
  enabled: boolean;
  mode: string;
  stage?: GoesStage;
  backend?: 'goestools' | 'simulate';
  simulate?: boolean;
  downlink_mode?: 'hrit' | 'lrit';
  downlink_freq_mhz?: number;
  symbol_rate_baud?: number;
  latest_timestamp?: number | null;
  fault_detail?: string | null;
  products_total?: number;
}
